name: macos build

on:
  push:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: clone
        run: git clone https://github.com/open-telemetry/opentelemetry-php-instrumentation

      - name: build
        run: |
          cd opentelemetry-php-instrumentation/ext
          phpize
          ./configure
          make

      - name: test
        env:
          TEST_PHP_ARGS: "-q" #do not try to submit failures
        run: make test TESTS=--show-diff
